# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RYBOTRON
email: ryan@rybotron.com
description: "Rybotron is me, Ryan Berkey, and my open source visual creation and idea lab."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rybotron.com" # the base hostname & protocol for your site
twitter_username: rybotron
github_username:  rybotron

# Build settings
markdown: kramdown
